# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_is_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
