# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canalis_door', '0002_auto_20180716_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdoor',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
